# permissions for end users to edit koorclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: koorcluster-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: koor-operator
    app.kubernetes.io/part-of: koor-operator
    app.kubernetes.io/managed-by: kustomize
  name: koorcluster-editor-role
rules:
- apiGroups:
  - storage.koor.tech
  resources:
  - koorclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.koor.tech
  resources:
  - koorclusters/status
  verbs:
  - get
