# Namespace where the operator and other rook resources are created
apiVersion: v1
kind: Namespace
metadata:
  name: koor-ceph # namespace:cluster
---
apiVersion: storage.koor.tech/v1alpha1
kind: KoorCluster
metadata:
  labels:
    app.kubernetes.io/name: koorcluster
    app.kubernetes.io/instance: koorcluster-sample
    app.kubernetes.io/part-of: koor-operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: koor-operator
  name: koorcluster-sample
  namespace: koor-ceph
spec:
  useAllDevices: true
  monitoringEnabled: true
  dashboardEnabled: true
  toolboxEnabled: true
