//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023 Koor Technologies, Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DetailedProductVersions) DeepCopyInto(out *DetailedProductVersions) {
	*out = *in
	if in.KoorOperator != nil {
		in, out := &in.KoorOperator, &out.KoorOperator
		*out = new(DetailedVersion)
		**out = **in
	}
	if in.Ksd != nil {
		in, out := &in.Ksd, &out.Ksd
		*out = new(DetailedVersion)
		**out = **in
	}
	if in.Ceph != nil {
		in, out := &in.Ceph, &out.Ceph
		*out = new(DetailedVersion)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DetailedProductVersions.
func (in *DetailedProductVersions) DeepCopy() *DetailedProductVersions {
	if in == nil {
		return nil
	}
	out := new(DetailedProductVersions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DetailedVersion) DeepCopyInto(out *DetailedVersion) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DetailedVersion.
func (in *DetailedVersion) DeepCopy() *DetailedVersion {
	if in == nil {
		return nil
	}
	out := new(DetailedVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KoorCluster) DeepCopyInto(out *KoorCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KoorCluster.
func (in *KoorCluster) DeepCopy() *KoorCluster {
	if in == nil {
		return nil
	}
	out := new(KoorCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KoorCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KoorClusterList) DeepCopyInto(out *KoorClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KoorCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KoorClusterList.
func (in *KoorClusterList) DeepCopy() *KoorClusterList {
	if in == nil {
		return nil
	}
	out := new(KoorClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KoorClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KoorClusterSpec) DeepCopyInto(out *KoorClusterSpec) {
	*out = *in
	if in.UseAllDevices != nil {
		in, out := &in.UseAllDevices, &out.UseAllDevices
		*out = new(bool)
		**out = **in
	}
	if in.MonitoringEnabled != nil {
		in, out := &in.MonitoringEnabled, &out.MonitoringEnabled
		*out = new(bool)
		**out = **in
	}
	if in.DashboardEnabled != nil {
		in, out := &in.DashboardEnabled, &out.DashboardEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ToolboxEnabled != nil {
		in, out := &in.ToolboxEnabled, &out.ToolboxEnabled
		*out = new(bool)
		**out = **in
	}
	out.UpgradeOptions = in.UpgradeOptions
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KoorClusterSpec.
func (in *KoorClusterSpec) DeepCopy() *KoorClusterSpec {
	if in == nil {
		return nil
	}
	out := new(KoorClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KoorClusterStatus) DeepCopyInto(out *KoorClusterStatus) {
	*out = *in
	in.TotalResources.DeepCopyInto(&out.TotalResources)
	out.CurrentVersions = in.CurrentVersions
	if in.LatestVersions != nil {
		in, out := &in.LatestVersions, &out.LatestVersions
		*out = new(DetailedProductVersions)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KoorClusterStatus.
func (in *KoorClusterStatus) DeepCopy() *KoorClusterStatus {
	if in == nil {
		return nil
	}
	out := new(KoorClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProductVersions) DeepCopyInto(out *ProductVersions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProductVersions.
func (in *ProductVersions) DeepCopy() *ProductVersions {
	if in == nil {
		return nil
	}
	out := new(ProductVersions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Resources) DeepCopyInto(out *Resources) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Cpu != nil {
		in, out := &in.Cpu, &out.Cpu
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Resources.
func (in *Resources) DeepCopy() *Resources {
	if in == nil {
		return nil
	}
	out := new(Resources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeOptions) DeepCopyInto(out *UpgradeOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeOptions.
func (in *UpgradeOptions) DeepCopy() *UpgradeOptions {
	if in == nil {
		return nil
	}
	out := new(UpgradeOptions)
	in.DeepCopyInto(out)
	return out
}
