# NOTE: commit your changes before running make or they will be lost.
certmanager:
  # -- Install cert-manger. Set to false to use an existing cert-manager
  enabled: true
  # -- If cert-manager's CRDs should be installed through Helm
  installCRDs: true
controllerManager:
  # RBAC proxy configuration
  kubeRbacProxy:
    # -- RBAC proxy args
    args:
    - --secure-listen-address=0.0.0.0:8443
    - --upstream=http://127.0.0.1:8080/
    - --logtostderr=true
    - --v=0
    # -- RBAC proxy container security context
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      # -- Operator image repository
      repository: gcr.io/kubebuilder/kube-rbac-proxy
      # -- Operator image tag
      tag: v0.14.1
    # -- RBAC proxy container resources
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 5m
        memory: 64Mi
  # Operator configuration
  manager:
    # -- Operator args
    args:
    - --health-probe-bind-address=:8081
    - --metrics-bind-address=127.0.0.1:8080
    - --leader-elect
    # -- Operator container security context
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      # -- Operator image repository
      repository: docker.io/koorinc/koor-operator
      # -- Operator image tag
      tag: v0.3.8
    # -- Operator container resources
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 128Mi
  replicas: 1
  serviceAccount:
    annotations: {}
kubernetesClusterDomain: cluster.local
# -- Metrics Service
metricsService:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  type: ClusterIP
# -- Webhook service
webhookService:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  type: ClusterIP
# This is appeneded to values.yaml from additional-values.yaml. This is a hack to avoid getting these values overwritten by helmify

# Koor Cluster specification
koorCluster:
  spec:
    # -- If all empty + unused devices of the cluster should be used.
    useAllDevices: true
    # -- If monitoring should be enabled, requires the prometheus-operator to be pre-installed.
    monitoringEnabled: true
    # -- Enable the Ceph MGR dashboard.
    dashboardEnabled: true
    # -- If the Ceph toolbox, should be deployed as well.
    toolboxEnabled: true
    upgradeOptions:
      # -- Upgrade mode. Options: disabled, notify, upgrade.
      mode: notify
      # -- The api endpoint used to find the ceph latest version
      endpoint: https://versions.koor.tech
      # -- The schedule to check for new versions. Uses CRON format as specified by https://github.com/robfig/cron/tree/v3.
      # Defaults to everyday at midnight in the local timezone.
      # To change the timezone, prefix the schedule with CRON_TZ=<Timezone>.
      # For example: "CRON_TZ=UTC 0 0 * * *" is midnight UTC.
      schedule: 0 0 * * *
    # -- The name to use for KSD helm release.
    ksdReleaseName: ksd
    # -- The name to use for KSD cluster helm release.
    ksdClusterReleaseName: ksd-cluster
