# If true, create & use PSP resources
pspEnable: false

monitoring:
  # Enable monitoring. Requires Prometheus to be pre-installed.
  # Enabling will also create RBAC rules to allow Operator to create ServiceMonitors
  enabled: {{ .Spec.MonitoringEnabled  | default true }}
