apiVersion: storage.koor.tech/v1alpha1
kind: KoorCluster
metadata:
  labels:
    app.kubernetes.io/name: koorcluster
    app.kubernetes.io/instance: {{ .Release.Namespace }}
    app.kubernetes.io/part-of: koor-operator
  name: {{ .Release.Namespace }}
spec:
{{ toYaml .Values.koorClusterSpec | indent 2 }}
