apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "koor-operator.fullname" . }}-manager-role
  labels:
  {{- include "koor-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes/status
  verbs:
  - get
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - storage.koor.tech
  resources:
  - koorclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.koor.tech
  resources:
  - koorclusters/finalizers
  verbs:
  - update
- apiGroups:
  - storage.koor.tech
  resources:
  - koorclusters/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "koor-operator.fullname" . }}-manager-rolebinding
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: koor-operator
    app.kubernetes.io/part-of: koor-operator
  {{- include "koor-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "koor-operator.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "koor-operator.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'