name: Helm gen
on:
  push:
    tags:
      - v*
    branches:
      - main
      - release-*
  pull_request:
    branches:
      - main
      - release-*

# cancel the in-progress workflow when PR is refreshed.
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  helm-gen:
    name: helm-gen
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: run helm-gen
        run: GOPATH=$(go env GOPATH) make helm

      - name: validate helm-gen
        run: scripts/validate_modified_files.sh helm
