name: Unit tests
on:
  push:
    tags:
      - v*
    branches:
      - main
      - release-*
  pull_request:

# cancel the in-progress workflow when PR is refreshed.
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  unittests:
    runs-on: ubuntu-20.04
    if: "!contains(github.event.pull_request.labels.*.name, 'skip-ci')"
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v4
        with:
          go-version: ^1.20

      - name: ensure generate is noop
        run: GOPATH=$(go env GOPATH) make ensure-generate-is-noop

      - name: run unit tests
        run: GOPATH=$(go env GOPATH) make -j $(nproc) test
